---
- ansible.builtin.include_tasks: install.yaml
  when: "ansible_system == 'Linux'"

- ansible.builtin.include_tasks: service-Debian.yaml
  when: "ansible_os_family == 'Debian'"

- ansible.builtin.include_tasks: service-FreeBSD.yaml
  when: "ansible_os_family == 'FreeBSD'"
