---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check Varnish status
      register: varnish_systemd
      ansible.builtin.command:
        cmd: systemctl status varnish

    - name: Check Varnishncsa status
      register: varnishncsa_systemd
      ansible.builtin.command:
        cmd: systemctl status varnishncsa

    - name: Debug
      debug:
        var: varnish_systemd.stdout

    - name: Debug
      debug:
        var: varnishncsa_systemd.stdout
